# Generated by Django 3.0.3 on 2020-03-01 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicationuser',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('user_satus', models.CharField(choices=[('provider', 'PROVIDER'), ('seeker', 'SEEKER')], max_length=10)),
                ('phonenumber', models.CharField(max_length=10)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='pic/')),
                ('address', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('request', 'REQUEST'), ('accept', 'ACCEPT')], default='request', max_length=10)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_provider', to='core.Applicationuser')),
                ('seeker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker', to='core.Applicationuser')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('ammount', models.CharField(max_length=10)),
                ('payment_status', models.CharField(choices=[('pending', 'PENDING'), ('done', 'DONE')], default='pending', max_length=10)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Job')),
            ],
        ),
    ]
